STUBS_DEFAULT_PATH = 'stubs'
PLAYER_DETECTOR_MODEL_PATH = 'models/player_detector.pt'
BALL_DETECTOR_MODEL_PATH = 'models/ball_detector_model.pt'
KEYPOINT_DETECTOR_MODEL_PATH = 'models/court_keypoint_detector.pt'
OUTPUT_VIDEO_PATH = 'output_videos/output_video.mp4'